local quill = require("util.quill")

return quill({
  LEADER = "<localleader>",
  guid = {
    LEADER = { append = "G" },
    uppercase = "G",
    lowercase = "g",
  },
  notes = {
    LEADER = { append = "n" },
    eureka = "n",
    weaver = {
      LEADER = { append = "w" },
      current_buffer = "w",
      global = "g",
    },
  },
  venn = "v",
  figlet = {
    LEADER = { append = "f" },
    change_font = "F",
    ascii_interface = "f",
    ascii_comment_interface = "c",
    banner = {
      LEADER = { append = "b" },
      change_font = "F",
      generate = "b",
    },
  },
  textgen = "t",
  significant = {
    LEADER = { append = "g" },
    start_signs = "s",
  },
  cbox = {
    LEADER = { append = "b" },
    catalog = "b",
    pos_left = {
      LEADER = { append = "l" },
      align_left = "l",
      align_center = "c",
      align_right = "r",
    },
    pos_center = {
      LEADER = { append = "c" },
      align_left = "l",
      align_center = "c",
      align_right = "r",
    },
    pos_right = {
      LEADER = { append = "r" },
      align_left = "l",
      align_center = "c",
      align_right = "r",
    },
    adaptive = {
      LEADER = { append = "a" },
      align_left = "l",
      align_center = "c",
      align_right = "r",
    },
  },
  cline = {
    LEADER = { append = "l" },
    align_left = {
      LEADER = { append = "l" },
      text_left = "l",
      text_center = "c",
      text_right = "r",
    },
    align_center = {
      LEADER = { append = "c" },
      text_left = "l",
      text_center = "c",
      text_right = "r",
    },
    align_right = {
      LEADER = { append = "r" },
      text_left = "l",
      text_center = "c",
      text_right = "r",
    },
    custom = {
      LEADER = { append = "b" },
      comment = { insert = "c", nospace = "C" },
      dash = { insert = "d", nospace = "D" },
      select = { insert = "s", nospace = "S" },
      following = { insert = "f", nospace = "F" },
    },
  },
  silicon = {
    LEADER = { append = "S" },
    save = "S",
    copy = "C",
    file = "F",
  },
  modeline = "m",
  licenses = {
    LEADER = { append = "c" },
    insert = "I",
    fetch = "F",
    update = "u",
    write = "W",
    select_insert = "i",
    select_fetch = "f",
    select_write = "w",
  },
  glyph = {
    LEADER = { append = "y" },
    nerdfonts = "n",
    nerdy = "y",
    nerdicons = "i",
    picker = {
      LEADER = { append = "p" },
      normal = {
        everything = "p",
        icons = "i",
        emoji = "e",
        nerd = "n",
        nerdv2 = "N",
        symbols = "y",
        altfont = "f",
        altfontsymbols = "F",
      },
      yank = {
        everything = "p",
        icons = "i",
        emoji = "e",
        nerd = "n",
        nerdv2 = "N",
        symbols = "y",
        altfont = "f",
        altfontsymbols = "F",
      },
      insert = {
        everything = "p",
        icons = "i",
        emoji = "e",
        nerd = "n",
        nerdv2 = "N",
        symbols = "y",
        altfont = "f",
        altfontsymbols = "F",
      },
    },
    unicode = {
      LEADER = { append = "u" },
      digraphs = "g",
      search = "s",
      search_add = "S",
      name = "n",
      table = "t",
      update = "U",
    },
  },
  comment_frame = {
    LEADER = { append = "c" },
    single_line = "f",
    multi_line = "m",
  },
  template = {
    LEADER = { append = "t" },
    buffet = "b",
    select = "t",
    edit = "e",
  },
  wrapping = {
    LEADER = { append = "w" },
    mode = {
      hard = "h",
      soft = "s",
      toggle = "w",
    },
    log = "l",
  },
  workspaces = {
    LEADER = { append = "e" },
  },
})
