local quill = require("util.quill")

return quill({
  LEADER = "<leader><leader>",
  files = {
    LEADER = { append = "f" },
    files = "f",
    recent = "r",
    directories = "d",
  },
  buffers = {
    LEADER = { append = "b" },
    buffers = "b",
    lines = "l",
    all_lines = "L",
  },
  quickfix = {
    LEADER = { append = "q" },
    qf = "f",
    stack = "F",
  },
  loclist = {
    LEADER = { append = "l" },
    list = "l",
    stack = "L",
  },
  arguments = "r",
  grep = {
    LEADER = { append = "g" },
    everything = "g",
    last = "l",
    cword = "w",
    cWORD = "W",
    visual = "v",
    project = "p",
    curbuf = "b",
  },
  live_grep = {
    LEADER = { append = "v" },
    everything = "p",
    curbuf = "b",
    resume = "r",
    glob = "g",
  },
  git = {
    LEADER = { append = "g" },
    files = "f",
    status = "s",
    commits = "c",
    bufcommits = "C",
    branches = "b",
    stash = "h",
  },
  lsp = {
    LEADER = { append = "l" },
    references = "r",
    definitions = "d",
    declarations = "D",
    type_definitions = "y",
    implementations = "i",
    finder = "f",
  },
  code = {
    LEADER = { append = "c" },
    symbols = {
      LEADER = { append = "s" },
      document = "d",
      workspace = "w",
      workspace_live = "l",
    },
    code_actions = "a",
    calls = {
      incoming = "i",
      outgoing = "o",
    },
  },
  diagnostics = {
    LEADER = { append = "d" },
    workspace = "w",
    document = "d",
  },
  dap = {
    LEADER = { append = "d" },
    commands = "c",
    configurations = "C",
    breakpoints = "b",
    variables = "v",
    frames = "f",
  },
  resume = "<leader>",
  builtin = "B",
  fzf_profiles = "p",
  help = {
    LEADER = { append = "h" },
    tags = "h",
    man = "m",
  },
  colors = {
    LEADER = { append = "C" },
    schemes = "s",
    highlights = "h",
  },
  history = {
    LEADER = { append = "h" },
    command = ":",
    search = "/",
  },
  tags = {
    LEADER = { append = "t" },
    project = "t",
    buffer = "b",
    grep = {
      LEADER = { append = "g" },
      project = "t",
      cword = "w",
      cWORD = "W",
      visual = "t",
      live = "l",
    },
  },
  neovim_cmd = ":",
  marks = "`",
  jumps = "j",
  changes = "u",
  registers = '"',
  tagstack = "T",
  autocmd = "a",
  keymaps = "k",
  filetypes = "ft",
  menus = "m",
  spelling = "z",
})
