local quill = require("util.quill")

return quill({
  LEADER = "<leader>g",
  log = "l",
  neogit = "n",
  diffview = "d",
  blame = {
    LEADER = { append = "b" },
    toggle = "b",
    enable = "e",
    toggle_alt = "B",
    mode_insert = "i",
    mode_visual = "v",
  },
  conflict = {
    LEADER = { append = "c" },
    choose_both = "b",
    choose_none = "e",
    choose_ours = "o",
    choose_theirs = "t",
    next = "n",
    previous = "p",
    quickfix = "q",
  },
  hunk = {
    LEADER = { append = "h" },
    blame_line = "b",
    diff = "d",
    altdiff = "D",
    preview = "p",
    reset = "r",
    reset_buffer = "R",
    stage = "s",
    stage_buffer = "S",
    undo_stage = "u",
  },
  gitsigns = {
    LEADER = { append = "s" },
    toggle = {
      linehl = "l",
      numhl = "n",
      signs = "s",
      word_diff = "w",
      line_blame = "b",
      deleted = "d",
    },
    reset = {
      LEADER = { append = "R" },
      buffer = "b",
      hunk = "h",
      base = "B",
    },
    diffthis = "d",
    refresh = "r",
    preview = {
      LEADER = { append = "p" },
      hunk_inline = "i",
      hunk = "h",
    },
  },
  gh_actions = "a",
  tardis = "t",
  fugit = {
    LEADER = { append = "f" },
    open = "f",
    diff = "d",
    graph = "g",
  },
  ignore = {
    LEADER = { append = "i" },
    generate = "i",
    licenses = "l",
  },
})
