local quill = require("util.quill")

return quill({
  LEADER = "Z",
  lsp_capabilities = "l",
  notice = "N",
  builtin = "i",
  pickers = {
    LEADER = { append = "o" },
    builtin = "b",
    all = "o",
    extensions = "x",
  },
  treesitter = "t",
  files = {
    LEADER = { append = "f" },
    find = "f",
    browser = "F",
    recent = "r",
    frecency = "y",
    media = "m",
    dir = "d",
  },
  toggleterm = "<localleader>",
  repo = "r",
  env = "e",
  changes = "u",
  lazy = "L",
  menu = "M",
  luasnip = "s",
  project = "p",
  zoxide = "z",
  workspaces = "S",
  dap = {
    LEADER = { append = "d" },
    commands = "c",
    configurations = "C",
    list_breakpoints = "b",
    variables = "v",
    frames = "f",
  },
  conventional_commits = "C",
  undo = "u",
  color_names = "c",
  neoclip = "v",
  http = "H",
  ports = "P",
  all_recent = "R",
  tasks = "'",
  whaler = "w",
  glymbol = {
    LEADER = { append = "y" },
    symbols = "s",
    glyph = "g",
  },
  media_files = "X",
  heading = "#",
  neorg = "n",
  diagnostic = {
    LEADER = { append = "d" },
    error_lens = "l",
  },
  pineapple = "C",
})
